<?php
/**
 * Description: Advanced custom fields as php code
 */

if(function_exists("register_field_group"))
{
  register_field_group(array (
    'id' => 'acf_first-column-layout',
    'title' => 'First column layout',
    'fields' => array (
      array (
        'key' => 'field_5ede01bbf6bc6',
        'label' => 'First column content',
        'name' => 'left_column_content',
        'type' => 'repeater',
        'instructions' => 'Content for the first column',
        'sub_fields' => array (
          array (
            'key' => 'field_5ede04d6f24c1',
            'label' => 'Content type',
            'name' => 'content_type',
            'type' => 'select',
            'instructions' => 'Which kind of content you would like to add',
            'column_width' => '',
            'choices' => array (
              'text' => 'text',
              'person' => 'person',
              'cta-subfield' => 'button',
              'image-and-text' => 'Image and text',
              'icons' => 'icons',
            ),
            'default_value' => '',
            'allow_null' => 0,
            'multiple' => 0,
          ),
          array (
            'key' => 'field_5ede063242ae9',
            'label' => 'Text content',
            'name' => 'text_content',
            'type' => 'wysiwyg',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ede04d6f24c1',
                  'operator' => '==',
                  'value' => 'text',
                ),
              ),
              'allorany' => 'any',
            ),
            'column_width' => '',
            'default_value' => '',
            'toolbar' => 'full',
            'media_upload' => 'yes',
          ),
          array (
            'key' => 'field_5ede067942aea',
            'label' => 'Image',
            'name' => 'image',
            'type' => 'image',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ede04d6f24c1',
                  'operator' => '==',
                  'value' => 'image',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'save_format' => 'object',
            'preview_size' => 'full',
            'library' => 'all',
          ),
          array (
            'key' => 'field_5ede1d586408f',
            'label' => 'person',
            'name' => 'person',
            'type' => 'post_object',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ede04d6f24c1',
                  'operator' => '==',
                  'value' => 'person',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'post_type' => array (
              0 => 'people',
            ),
            'taxonomy' => array (
              0 => 'all',
            ),
            'allow_null' => 0,
            'multiple' => 0,
          ),
          array (
            'key' => 'field_5ee1f562a5d3f',
            'label' => 'Functionality',
            'name' => 'functionality',
            'type' => 'select',
            'instructions' => 'What is this button for?',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ede04d6f24c1',
                  'operator' => '==',
                  #'value' => 'text',
                  'value' => 'cta-subfield',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'choices' => array (
              'Internal link' => 'Internal link',
              'External link' => 'External link',
              'Sign in button' => 'Sign in button',
              'Advanced functionality' => 'Advanced functionality',
            ),
            'default_value' => '',
            'allow_null' => 0,
            'multiple' => 0,
          ),
          array (
            'key' => 'field_5ee1f591a5d40',
            'label' => 'Button text',
            'name' => 'button_text',
            'type' => 'text',
            'instructions' => 'Text on the button. Short and descriptive name, for example: "read more" or "sign in" or whatever this button is supposed to do.',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ede04d6f24c1',
                  'operator' => '==',
                  'value' => 'cta-subfield',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'formatting' => 'html',
            'maxlength' => '',
          ),
          array (
            'key' => 'field_5ee1f5afa5d41',
            'label' => 'Button url',
            'name' => 'button_url',
            'type' => 'post_object',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ede04d6f24c1',
                  'operator' => '==',
                  'value' => 'cta-subfield',
                ),
                array (
                  'field' => 'field_5ee1f562a5d3f',
                  'operator' => '==',
                  'value' => 'Internal link',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'post_type' => array (
              0 => 'post',
              1 => 'page',
            ),
            'taxonomy' => array (
              0 => 'all',
            ),
            'allow_null' => 0,
            'multiple' => 0,
          ),
          array (
            'key' => 'field_5ee1f5cea5d43',
            'label' => 'External url',
            'name' => 'external_url',
            'type' => 'text',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ede04d6f24c1',
                  'operator' => '==',
                  'value' => 'cta-subfield',
                ),
                array (
                  'field' => 'field_5ee1f562a5d3f',
                  'operator' => '==',
                  'value' => 'External link',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'default_value' => '',
            'placeholder' => 'https://www......',
            'prepend' => '',
            'append' => '',
            'formatting' => 'html',
            'maxlength' => '',
          ),
          array (
            'key' => 'field_5ee1f5fba5d45',
            'label' => 'Class',
            'name' => 'class',
            'type' => 'text',
            'instructions' => 'Add class for wow-modal popup',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ede04d6f24c1',
                  'operator' => '==',
                  'value' => 'cta-subfield',
                ),
                array (
                  'field' => 'field_5ee1f562a5d3f',
                  'operator' => '==',
                  'value' => 'Advanced functionality',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'formatting' => 'html',
            'maxlength' => '',
          ),
          array (
            'key' => 'field_5ee1f64ae998b',
            'label' => 'Text',
            'name' => 'text-with-image',
            'type' => 'wysiwyg',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ede04d6f24c1',
                  'operator' => '==',
                  'value' => 'image-and-text',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'default_value' => '',
            'toolbar' => 'full',
            'media_upload' => 'no',
          ),
          array (
            'key' => 'field_5ee1f695e998c',
            'label' => 'Image',
            'name' => 'image',
            'type' => 'image',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ede04d6f24c1',
                  'operator' => '==',
                  'value' => 'image-and-text',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'save_format' => 'object',
            'preview_size' => 'thumbnail',
            'library' => 'all',
          ),
          array (
            'key' => 'field_5ee1f6a5e998d',
            'label' => 'Image position',
            'name' => 'image_position',
            'type' => 'radio',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ede04d6f24c1',
                  'operator' => '==',
                  'value' => 'image-and-text',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'choices' => array (
              'left' => 'Left',
              'right' => 'Right',
            ),
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => 'left',
            'layout' => 'vertical',
          ),
          array (
            'key' => 'field_5ee9b6cf61c40',
            'label' => 'Icons',
            'name' => 'icons',
            'type' => 'repeater',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ede04d6f24c1',
                  'operator' => '==',
                  'value' => 'icons',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'sub_fields' => array (
              array (
                'key' => 'field_5ee9b6d661c41',
                'label' => 'Icon',
                'name' => 'icon',
                'type' => 'image',
                'column_width' => '',
                'save_format' => 'object',
                'preview_size' => 'thumbnail',
                'library' => 'all',
              ),
              array (
                'key' => 'field_5ee9b6e961c42',
                'label' => 'Title',
                'name' => 'title',
                'type' => 'text',
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
              array (
                'key' => 'field_5ee9b6f061c43',
                'label' => 'Url',
                'name' => 'url',
                'type' => 'text',
                'instructions' => 'url where clicking the icon leads',
                'column_width' => '',
                'default_value' => '',
                'placeholder' => 'https://www....',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
            ),
            'row_min' => '',
            'row_limit' => '',
            'layout' => 'table',
            'button_label' => 'Add Row',
          ),
        ),
        'row_min' => '',
        'row_limit' => '',
        'layout' => 'row',
        'button_label' => 'Add more content',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'one-column-template.php',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
      array (
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'two-column-template.php',
          'order_no' => 0,
          'group_no' => 1,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'no_box',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => -60,
  ));
  register_field_group(array (
    'id' => 'acf_second-column-layout',
    'title' => 'Second column layout',
    'fields' => array (
      array (
        'key' => 'field_5ee1e6013f1f3',
        'label' => 'Second column content',
        'name' => 'right_column_content',
        'type' => 'repeater',
        'instructions' => 'Content for the second column',
        'sub_fields' => array (
          array (
            'key' => 'field_5ee1e60c3f1f4',
            'label' => 'Content type',
            'name' => 'content_type',
            'type' => 'select',
            'instructions' => 'Content for the first column on the page',
            'column_width' => '',
            'choices' => array (
              'text' => 'text',
              'person' => 'person',
              'cta-subfield' => 'button',
              'image-and-text' => 'Image and text',
              'icons' => 'icons',
            ),
            'default_value' => '',
            'allow_null' => 0,
            'multiple' => 0,
          ),
          array (
            'key' => 'field_5ee1fe1997270',
            'label' => 'Text content',
            'name' => 'text_content',
            'type' => 'wysiwyg',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ee1e60c3f1f4',
                  'operator' => '==',
                  'value' => 'text',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'default_value' => '',
            'toolbar' => 'full',
            'media_upload' => 'yes',
          ),
          array (
            'key' => 'field_5ee1fe3497271',
            'label' => 'Person',
            'name' => 'person',
            'type' => 'post_object',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ee1e60c3f1f4',
                  'operator' => '==',
                  'value' => 'person',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'post_type' => array (
              0 => 'people',
            ),
            'taxonomy' => array (
              0 => 'all',
            ),
            'allow_null' => 0,
            'multiple' => 0,
          ),
          array (
            'key' => 'field_5ee1fe5e97272',
            'label' => 'Functionality',
            'name' => 'functionality',
            'type' => 'select',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ee1e60c3f1f4',
                  'operator' => '==',
                  'value' => 'cta-subfield',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'choices' => array (
              'Internal link' => 'Internal link',
              'External link' => 'External link',
              'Sign in button' => 'Sign in button',
              'Advanced functionality' => 'Advanced functionality',
            ),
            'default_value' => '',
            'allow_null' => 0,
            'multiple' => 0,
          ),
          array (
            'key' => 'field_5ee1fe7397273',
            'label' => 'Button text',
            'name' => 'button_text',
            'type' => 'text',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ee1e60c3f1f4',
                  'operator' => '==',
                  'value' => 'cta-subfield',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'formatting' => 'html',
            'maxlength' => '',
          ),
          array (
            'key' => 'field_5ee1feac97274',
            'label' => 'Button url',
            'name' => 'button_url',
            'type' => 'post_object',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ee1e60c3f1f4',
                  'operator' => '==',
                  'value' => 'cta-subfield',
                ),
                array (
                  'field' => 'field_5ee1fe5e97272',
                  'operator' => '==',
                  'value' => 'Internal link',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'post_type' => array (
              0 => 'post',
              1 => 'page',
            ),
            'taxonomy' => array (
              0 => 'all',
            ),
            'allow_null' => 0,
            'multiple' => 0,
          ),
          array (
            'key' => 'field_5ee1fee197276',
            'label' => 'External url',
            'name' => 'external_url',
            'type' => 'text',
            'instructions' => 'Url to external content',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ee1e60c3f1f4',
                  'operator' => '==',
                  'value' => 'cta-subfield',
                ),
                array (
                  'field' => 'field_5ee1fe5e97272',
                  'operator' => '==',
                  'value' => 'External link',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'default_value' => '',
            'placeholder' => 'https://www...',
            'prepend' => '',
            'append' => '',
            'formatting' => 'html',
            'maxlength' => '',
          ),
          array (
            'key' => 'field_5ee1ff1297277',
            'label' => 'Class',
            'name' => 'class',
            'type' => 'text',
            'instructions' => 'Add class for wow-modal popup',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ee1e60c3f1f4',
                  'operator' => '==',
                  'value' => 'cta-subfield',
                ),
                array (
                  'field' => 'field_5ee1fe5e97272',
                  'operator' => '==',
                  'value' => 'Advanced functionality',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'formatting' => 'html',
            'maxlength' => '',
          ),
          array (
            'key' => 'field_5ee1ff2097278',
            'label' => 'Text',
            'name' => 'text-with-image',
            'type' => 'wysiwyg',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ee1e60c3f1f4',
                  'operator' => '==',
                  'value' => 'image-and-text',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'default_value' => '',
            'toolbar' => 'full',
            'media_upload' => 'no',
          ),
          array (
            'key' => 'field_5ee1ff4697279',
            'label' => 'Image',
            'name' => 'image',
            'type' => 'image',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ee1e60c3f1f4',
                  'operator' => '==',
                  'value' => 'image-and-text',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'save_format' => 'object',
            'preview_size' => 'thumbnail',
            'library' => 'all',
          ),
          array (
            'key' => 'field_5ee1ff599727a',
            'label' => 'Image position',
            'name' => 'image_position',
            'type' => 'radio',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ee1e60c3f1f4',
                  'operator' => '==',
                  'value' => 'image-and-text',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'choices' => array (
              'left' => 'Left',
              'right' => 'Right',
            ),
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'layout' => 'vertical',
          ),
          array (
            'key' => 'field_5ee9b7cd511b6',
            'label' => 'Icons',
            'name' => 'icons',
            'type' => 'repeater',
            'conditional_logic' => array (
              'status' => 1,
              'rules' => array (
                array (
                  'field' => 'field_5ee1e60c3f1f4',
                  'operator' => '==',
                  'value' => 'icons',
                ),
              ),
              'allorany' => 'all',
            ),
            'column_width' => '',
            'sub_fields' => array (
              array (
                'key' => 'field_5ee9b7d4511b7',
                'label' => 'Image',
                'name' => 'image',
                'type' => 'image',
                'column_width' => '',
                'save_format' => 'object',
                'preview_size' => 'thumbnail',
                'library' => 'all',
              ),
              array (
                'key' => 'field_5ee9b7de511b8',
                'label' => 'Title',
                'name' => 'title',
                'type' => 'text',
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
              array (
                'key' => 'field_5ee9b7e9511b9',
                'label' => 'Url',
                'name' => 'url',
                'type' => 'text',
                'instructions' => 'url where clicking the icon leads',
                'column_width' => '',
                'default_value' => '',
                'placeholder' => 'https://www...',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
            ),
            'row_min' => '',
            'row_limit' => '',
            'layout' => 'table',
            'button_label' => 'Add Row',
          ),
        ),
        'row_min' => '',
        'row_limit' => '',
        'layout' => 'row',
        'button_label' => 'Add Row',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'two-column-template.php',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'no_box',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => -50,
  ));
  register_field_group(array (
    'id' => 'acf_access-restriction',
    'title' => 'Access restriction',
    'fields' => array (
      array (
        'key' => 'field_5edf306a34694',
        'label' => 'Authenticated users only',
        'name' => 'authenticated_users_only',
        'type' => 'true_false',
        'instructions' => 'This content should be only visible for authenticated users',
        'message' => '',
        'default_value' => 0,
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'post',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'page',
          'order_no' => 0,
          'group_no' => 1,
        ),
      ),
    ),
    'options' => array (
      'position' => 'side',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_additional-graphical-elements',
    'title' => 'Additional graphical elements',
    'fields' => array (
      array (
        'key' => 'field_5ee34fa86a2aa',
        'label' => 'Add additional graphical elements',
        'name' => 'additional_graphical_elements',
        'type' => 'true_false',
        'instructions' => 'Add background wave elements to the layout',
        'message' => '',
        'default_value' => 1,
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'one-column-template.php',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
      array (
        array (
          'param' => 'page_template',
          'operator' => '==',
          'value' => 'two-column-template.php',
          'order_no' => 0,
          'group_no' => 1,
        ),
      ),
    ),
    'options' => array (
      'position' => 'side',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_cta-button',
    'title' => 'Cta-button',
    'fields' => array (
      array (
        'key' => 'field_5eddf5b97b11f',
        'label' => 'Enable cta-button',
        'name' => 'enable_cta-button',
        'type' => 'true_false',
        'instructions' => 'Is action button enabled ?',
        'message' => '',
        'default_value' => 0,
      ),
      array (
        'key' => 'field_5eddf15013a56',
        'label' => 'Functionality',
        'name' => 'functionality',
        'type' => 'radio',
        'instructions' => 'What is this button for?',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_5eddf5b97b11f',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'choices' => array (
          'Internal link' => 'Internal link',
          'External link' => 'External link',
          'Sign in button' => 'Sign in button',
          'Advanced functionality' => 'Advanced functionality',
        ),
        'other_choice' => 0,
        'save_other_choice' => 0,
        'default_value' => '',
        'layout' => 'horizontal',
      ),
      array (
        'key' => 'field_5eddf04f39dcb',
        'label' => 'Button text',
        'name' => 'button_text',
        'type' => 'text',
        'instructions' => 'Text on the button. Short and descriptive name, for example: "read more" or "sign in" or whatever this button is supposed to do.',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_5eddf5b97b11f',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'any',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5eddee3e7c573',
        'label' => 'Button url',
        'name' => 'button_url',
        'type' => 'page_link',
        'instructions' => 'Select content where you would like the button to lead',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_5eddf15013a56',
              'operator' => '==',
              'value' => 'Internal link',
            ),
            array (
              'field' => 'field_5eddf5b97b11f',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'post_type' => array (
          0 => 'post',
          1 => 'page',
        ),
        'allow_null' => 0,
        'multiple' => 0,
      ),
      array (
        'key' => 'field_5eddeeb67c575',
        'label' => 'External url',
        'name' => 'external_url',
        'type' => 'text',
        'instructions' => 'Url to external content',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_5eddf15013a56',
              'operator' => '==',
              'value' => 'External link',
            ),
            array (
              'field' => 'field_5eddf5b97b11f',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
        'placeholder' => 'https://www......',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5eddf3579b411',
        'label' => 'Class',
        'name' => 'class',
        'type' => 'text',
        'instructions' => 'Add class for wow-modal popup',
        'conditional_logic' => array (
          'status' => 1,
          'rules' => array (
            array (
              'field' => 'field_5eddf15013a56',
              'operator' => '==',
              'value' => 'Advanced functionality',
            ),
            array (
              'field' => 'field_5eddf5b97b11f',
              'operator' => '==',
              'value' => '1',
            ),
          ),
          'allorany' => 'all',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'page_type',
          'operator' => '==',
          'value' => 'front_page',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_front-page',
    'title' => 'Front page',
    'fields' => array (
      array (
        'key' => 'field_5eddea75f0bbb',
        'label' => 'images',
        'name' => 'images',
        'type' => 'repeater',
        'instructions' => 'logo images of partners',
        'sub_fields' => array (
          array (
            'key' => 'field_5eddead0f0bbc',
            'label' => 'image',
            'name' => 'image',
            'type' => 'image',
            'column_width' => '',
            'save_format' => 'object',
            'preview_size' => 'medium',
            'library' => 'all',
          ),
        ),
        'row_min' => '',
        'row_limit' => 12,
        'row_limit' => 9,
        'layout' => 'table',
        'button_label' => 'Add image',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'page',
          'operator' => '==',
          'value' => '19',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'no_box',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_hero-image-position',
    'title' => 'Hero image position',
    'fields' => array (
      array (
        'key' => 'field_5ee8ca95a5d90',
        'label' => 'Featured image position',
        'name' => 'hero_image_position',
        'type' => 'select',
        'instructions' => 'Horizontally align the hero image: which part of the image should be most visible in the hero area',
        'choices' => array (
          'Top' => 'Top',
          'Center' => 'Center',
          'Bottom' => 'Bottom',
        ),
        'default_value' => 'Center',
        'allow_null' => 0,
        'multiple' => 0,
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'page',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'side',
      'layout' => 'default',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
  register_field_group(array (
    'id' => 'acf_person',
    'title' => 'Person',
    'fields' => array (
      array (
        'key' => 'field_5ede0b560949a',
        'label' => 'Internal staff',
        'name' => 'internal_staff',
        'type' => 'true_false',
        'instructions' => 'This person is considered as spouse program internal staff',
        'message' => '',
        'default_value' => 1,
      ),
      array (
        'key' => 'field_5ede07e44f1bf',
        'label' => 'Name',
        'name' => 'name',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5ede08014f1c1',
        'label' => 'Title',
        'name' => 'title',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5ede07f54f1c0',
        'label' => 'Email',
        'name' => 'email',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5ede08754f1c2',
        'label' => 'Description',
        'name' => 'description',
        'type' => 'textarea',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'formatting' => 'br',
      ),
      array (
        'key' => 'field_5ede088d4f1c3',
        'label' => 'Phone',
        'name' => 'phone',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5ede08984f1c4',
        'label' => 'Availability',
        'name' => 'availability',
        'type' => 'text',
        'instructions' => 'When is this person available',
        'default_value' => '',
        'placeholder' => 'Mon 12:00 - 15:00...',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5ede08d94f1c5',
        'label' => 'Linkedin',
        'name' => 'linkedin',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_5ede090715f2f',
        'label' => 'Image',
        'name' => 'image',
        'type' => 'image',
        'save_format' => 'object',
        'preview_size' => 'thumbnail',
        'library' => 'all',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'people',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'normal',
      'layout' => 'no_box',
      'hide_on_screen' => array (
      ),
    ),
    'menu_order' => 0,
  ));
}
